// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiyvn9b3Oh6HzyYSWsyL4ttUaMiMlfw8',
    appId: '1:1008017717016:web:a0a6c0c54db27469ba506d',
    messagingSenderId: '1008017717016',
    projectId: 'incalss-11',
    authDomain: 'incalss-11.firebaseapp.com',
    storageBucket: 'incalss-11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD08Sqw5PyhwTka9SD8vJiqxkibXGC_mc',
    appId: '1:1008017717016:android:1d97629e93004eb1ba506d',
    messagingSenderId: '1008017717016',
    projectId: 'incalss-11',
    storageBucket: 'incalss-11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0nEyNv_QzbBdwZHlV-kOhUQXRJ3dCL3o',
    appId: '1:1008017717016:ios:7788f453c286014aba506d',
    messagingSenderId: '1008017717016',
    projectId: 'incalss-11',
    storageBucket: 'incalss-11.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0nEyNv_QzbBdwZHlV-kOhUQXRJ3dCL3o',
    appId: '1:1008017717016:ios:7788f453c286014aba506d',
    messagingSenderId: '1008017717016',
    projectId: 'incalss-11',
    storageBucket: 'incalss-11.firebasestorage.app',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSiyvn9b3Oh6HzyYSWsyL4ttUaMiMlfw8',
    appId: '1:1008017717016:web:1cb666595ad2e364ba506d',
    messagingSenderId: '1008017717016',
    projectId: 'incalss-11',
    authDomain: 'incalss-11.firebaseapp.com',
    storageBucket: 'incalss-11.firebasestorage.app',
  );
}
